# Generated by Django 5.1.7 on 2025-03-21 01:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_contentblogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
