# Generated by Django 5.1.7 on 2025-03-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_contentblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblog',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
