# Generated by Django 5.1.7 on 2025-03-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contentblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblog',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
