# Generated by Django 5.1.7 on 2025-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPerfom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('click_element', models.CharField(max_length=200)),
                ('scroll_position', models.CharField(max_length=20)),
                ('used_time', models.CharField(max_length=200)),
                ('user_agent', models.CharField(max_length=200)),
                ('see_user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
