# Generated by Django 5.1.7 on 2025-03-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('icon', models.CharField(default='', max_length=50, null=True)),
                ('contact', models.CharField(max_length=130)),
                ('update', models.DateTimeField(auto_now=True)),
                ('block', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=130)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('parent_id', models.CharField(max_length=2)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
