# Generated by Django 5.1.7 on 2025-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
