# Generated by Django 5.1.7 on 2025-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_menu_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.CharField(max_length=2),
        ),
    ]
